# Generated by Django 5.2.11 on 2026-02-15 13:37

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name = 'user',
            name = 'is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
